### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by anlonglong** [Alex-Jerry/Android-BLE#1]
在BluetoothLeService类中的disconnect()方法
public void disconnect(final String address) {
        if (mBluetoothAdapter == null || mBluetoothGattMap.get(address) == null) {//这里的条件为null
            Log.e(TAG,  mBluetoothGattMap.get(address).getDevice().getAddress());//这里用null掉方法了
            Log.w(TAG, "BluetoothAdapter not initialized");
            return;
        }

**Comment by AI-Curry** [comment]
Ok，Thank you for your reply, I will fix the problem
