### ISSUE TITLE
希望删除整个.idea目录，更新代码时总是冲突

### ISSUE THREAD

**Issue by tianshaokai** [Alex-Jerry/Android-BLE#16]

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/47370048-7e6b9700-d717-11e8-976a-cf36b3413aa8.png)

**Comment by tianshaokai** [comment]
这个idea目录其实没有什么用

**Comment by ai-curry** [comment]
已删除更新   你可以再试试
