### ISSUE TITLE
咨询一下SPP模块和BLE搜索结果不一样的问题，我的手机都支持BLE蓝牙，但是在BLE模块里面搜索，却搜索不出来

### ISSUE THREAD

**Issue by Achenglove** [Alex-Jerry/Android-BLE#19]

**Comment by AICareless** [comment]
spp是经典蓝牙模块，BLE是低功耗蓝牙模块，BLE模块下扫描不到设备，说明你周围并没有支持BLE4.0协议的设备，spp能扫描到是正常的，因为手机端打开蓝牙并对外可见，就能够通过spp模块被发现。

**Comment by Achenglove** [comment]
@AICareless 但是有些支持BLE4.0协议的设备在BLE模块可以被扫描出来，但是在SPP模块就扫描不出来哦，这是什么原因？扫描距离都是一样的

**Comment by Achenglove** [comment]
@AICareless 
![image](https://user-images.githubusercontent.com/26593441/52892519-fa5d8380-31cd-11e9-837d-e72450af89ac.png)华为8.0系统的BLE模块闪退

**Comment by AICareless** [comment]
你是运行的该蓝牙库的Demo还是说你移植到自己项目中报的错误，如果想得到更具体的答复建议你可以加到讨论群里494309361。

**Comment by Achenglove** [comment]
@AICareless 好，运行demo出现闪退
