### ISSUE TITLE
请问支持一对多吗? 

### ISSUE THREAD

**Issue by MAIMIHO** [Alex-Jerry/Android-BLE#2]

**Comment by MAIMIHO** [comment]
大佬的代码不一致啊, BleManager这个类
blelibrary中是
public class BleManager<T extends BleDevice>
compile 'cn.com.superLei:blelibrary:1.0.1'中没有泛型
public class BleManager

**Comment by AI-Curry** [comment]
这个其实已经更新过几次了，第三个版本就添加了泛型，因为改动较大，最新版本是1.0.4，实在抱歉，可以在readme中查看最新版本
