### ISSUE TITLE
怎么设置下，扫描列表只返回支持ble的设备，因为有很多name是空的

### ISSUE THREAD

**Issue by shuhao1022** [Alex-Jerry/Android-BLE#30]
怎么设置下，扫描列表只返回支持ble的设备，因为有很多name是空的

**Comment by aicareles** [comment]
拿到结果,过滤下name为空字符串就行了

**Comment by shuhao1022** [comment]
直接判断蓝牙名称是否为空，空的就不加进list发自我的iPhone------------------ 原始邮件 ------------------发件人: Allen Iverson  <notifications@github.com>发送时间: 2019年10月9日 11:47收件人: Alex-Jerry/Android-BLE <Android-BLE@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, Author <author@noreply.github.com>主题: 回复：[Alex-Jerry/Android-BLE] 怎么设置下，扫描列表只返回支持ble的设备，因为有很多name是空的 (#30)Closed #30.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Alex-Jerry/Android-BLE/issues/30?email_source=notifications\u0026email_token=AMB2BIKGWYY2FYRDN3YRVGLQNVH4DA5CNFSM4IW5IJ4KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUDEYQ7I#event-2697562237",
"url": "https://github.com/Alex-Jerry/Android-BLE/issues/30?email_source=notifications\u0026email_token=AMB2BIKGWYY2FYRDN3YRVGLQNVH4DA5CNFSM4IW5IJ4KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUDEYQ7I#event-2697562237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
